In [70]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [71]:
dataset = pd.read_csv('Dataset-Kasus-COVID19-shortened.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [72]:
print(x)

[['USA' 47916190 783565 37918301 1.6]
 ['India' 34447536 463655 33849785 1.3]
 ['Brazil' 21957967 611318 21151342 2.8]
 ['UK' 9561099 142898 7825200 1.5]
 ['Russia' 9109094 256597 7812557 2.8]
 ['Turki' 8408166 73531 7888959 0.9]
 ['Prancis' 7287645 118154 7009026 1.6]
 ['Iran' 6045212 128272 5708253 2.1]
 ['Argentina' 5305742 116232 5172193 2.2]
 ['Spanyol' 5047156 87673 4889801 1.7]]


In [73]:
print(y)

[79.1 98.3 96.3 81.8 85.8 93.8 96.2 94.4 97.5 96.9]


In [74]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [75]:
print(x)

[['USA' 47916190.0 783565.0 37918301 1.6]
 ['India' 34447536.0 463655.0 33849785 1.3]
 ['Brazil' 21957967.0 611318.0 21151342 2.8]
 ['UK' 9561099.0 142898.0 7825200 1.5]
 ['Russia' 9109094.0 256597.0 7812557 2.8]
 ['Turki' 8408166.0 73531.0 7888959 0.9]
 ['Prancis' 7287645.0 118154.0 7009026 1.6]
 ['Iran' 6045212.0 128272.0 5708253 2.1]
 ['Argentina' 5305742.0 116232.0 5172193 2.2]
 ['Spanyol' 5047156.0 87673.0 4889801 1.7]]


In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [77]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 47916190.0 783565.0 37918301
  1.6]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 34447536.0 463655.0 33849785
  1.3]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 21957967.0 611318.0 21151342
  2.8]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 9561099.0 142898.0 7825200 1.5]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 9109094.0 256597.0 7812557 2.8]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 8408166.0 73531.0 7888959 0.9]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 7287645.0 118154.0 7009026 1.6]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 6045212.0 128272.0 5708253 2.1]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5305742.0 116232.0 5172193 2.2]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 5047156.0 87673.0 4889801 1.7]]


In [78]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [79]:
print(y)

[0 9 6 1 2 3 5 4 8 7]


In [80]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [81]:
print(x_train)

[[0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 7287645.0 118154.0 7009026 1.6]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 9109094.0 256597.0 7812557 2.8]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 47916190.0 783565.0 37918301
  1.6]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 9561099.0 142898.0 7825200 1.5]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 34447536.0 463655.0 33849785
  1.3]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 6045212.0 128272.0 5708253 2.1]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 5305742.0 116232.0 5172193 2.2]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 8408166.0 73531.0 7888959 0.9]]


In [82]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 21957967.0 611318.0 21151342
  2.8]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 5047156.0 87673.0 4889801 1.7]]


In [83]:
print(y_train)

[5 2 0 1 9 4 8 3]


In [84]:
print(y_test)

[6 7]


In [85]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [86]:
print(x_train)

[[0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 -0.3779644730092272
  0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.5823209223104918 -0.6190086729904142 -0.565440909770907
  -0.27050089040023]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 2.6457513110645903
  0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.4607187329207765 -0.016392680227565765 -0.5017977139994038
  1.8935062328016077]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.0 -0.3779644730092272 -0.3779644730092272 2.6457513110645903
  2.130091022091229 2.2773985874728795 1.8827098647234566
  -0.27050089040023]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.0 -0.3779644730092272 2.6457513110645903 -0.3779644730092272
  -0.43054231973814094 -0.5113027570183252 -0.5007963326909799
  -0.45083481733371666]
 [0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.0 -0.3779644730092272 -0.3779644

In [87]:
print(x_test)

[[0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.3970879297913825 1.5276402255085881 0.5546928322383776
  1.8935062328016077]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  1.0 -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.7318987406867262 -0.7516866565316866 -0.7332928676404402
  -0.09016696346674373]]
